### ISSUE TITLE
Disconnecting and reconnecting to the Tango service results in a crash

### ISSUE THREAD

**Issue by yaustar** [google-ar/arcore-unity-sdk#19]
I've added the following code on SessionComponent 
```
        public void OnDestroy()
        {
            UnityTango.Device.Disconnect();
        }
```
Added buttons to load a non-ar scene and then from that scene, load back into HelloAR which results in the following crash:

```
09-22 13:43:25.631: E/Unity(7202): OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
09-22 13:43:25.631: E/Unity(7202):  
09-22 13:43:25.631: E/Unity(7202): (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 368)
09-22 13:43:26.546: E/Unity(7202): There was an error accessing the ARCore API.
09-22 13:43:26.546: E/Unity(7202):    at GoogleARCore.SessionComponent.Connect(GoogleARCore.SessionConfig sessionConfig)
09-22 13:43:26.546: E/Unity(7202):    at GoogleARCore.SessionComponent.Connect()
09-22 13:43:26.546: E/Unity(7202):    at GoogleARCore.SessionComponent.Awake()
09-22 13:43:26.546: E/Unity(7202):  
09-22 13:43:26.546: E/Unity(7202): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
09-22 13:43:26.547: I/Unity(7202): Connection state became ConnectToServiceFailed
09-22 13:43:26.547: I/Unity(7202):  
09-22 13:43:26.547: I/Unity(7202): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

Is there a way to stop/connect and/or pause the tango service for scenes that don't have AR features? 

Thanks!

**Comment by chaosemer** [comment]
Disconnecting from ARCore is not supported in the Unity developer preview. This will be addressed in the final 1.0 release.

For now, we recommend persisting the ARCore device across scenes with DontDestroyOnLoad.
