### ISSUE TITLE
Updating projects ARCore SDK from 1.4.1 to 1.5.0

### ISSUE THREAD

**Issue by kolboch** [google-ar/arcore-unity-sdk#405]
What is recommended way to update ARCore SDK in unity, when again import package it seems to replace files properly and add new ones but later project seems to be unrecoverable to work as previously ( building but later launches were unsuccessful).
Update from 1.4.1 to 1.5.0
Log after trying to launch same scene ( previously I deleted duplicated resources which raised complain of compiler ( like Google.JarResolver)
```
09-29 18:37:25.078 21064 21122 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-29 18:37:25.078 21064 21122 E CRASH   : Build fingerprint: 'lge/lucye_global_com/lucye:8.0.0/OPR1.170623.032/182292118abf4:user/release-keys'
09-29 18:37:25.078 21064 21122 E CRASH   : Revision: '12'
09-29 18:37:25.079 21064 21122 E CRASH   : pid: 21064, tid: 21122, name: UnityMain  >>> com.kakaboc.arcoremovement <<<
09-29 18:37:25.079 21064 21122 E CRASH   :     r0 00000000  r1 00000000  r2 e5402fc8  r3 00000000
09-29 18:37:25.079 21064 21122 E CRASH   :     r4 ba903440  r5 d93fe248  r6 e5402fc8  r7 e55c7fc0
09-29 18:37:25.079 21064 21122 E CRASH   :     r8 00000000  r9 00000003  sl bab9cd50  fp d93fe1a8
09-29 18:37:25.079 21064 21122 E CRASH   :     ip 80000000  sp d93fe154  lr c10e978b  pc e55ed2ea  cpsr e7a0fc90
09-29 18:37:25.079 21064 21122 E CRASH   :
09-29 18:37:25.079 21064 21122 E CRASH   : backtrace:
09-29 18:37:25.463 21064 21122 E CRASH   :      #00  pc 000192ea  /system/lib/libc.so (__memcpy_base_aligned+113)
09-29 18:37:25.463 21064 21122 E CRASH   :      #01  pc 00002787  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libarpresto_api.so (ArPrestoConfig_copy(ArPrestoConfig const&, ArPrestoConfig
09-29 18:37:25.463 21064 21122 E CRASH   :      #02  il ........  at (wrapper managed-to-native) GoogleARCoreInternal.ARCoreAndroidLifecycleManager/ExternApi.ArPresto_setConfiguration (GoogleARCoreInternal.ApiPres
09-29 18:37:25.463 21064 21122 E CRASH   :      #03  il 00000390  at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._SetConfiguration (GoogleARCore.ARCoreSessionConfig) [0x00075] in D:\Unity3dProjects\ARCoreMo
s\Managers\ARCoreAndroidLifecycleManager.cs:280
09-29 18:37:25.463 21064 21122 E CRASH   :      #04  il 0000017f  at GoogleARCoreInternal.ARCoreAndroidLifecycleManager.EnableSession () [0x00024] in D:\Unity3dProjects\ARCoreMovement\Assets\GoogleARCore\SDK\Scrip
ager.cs:104
09-29 18:37:25.463 21064 21122 E CRASH   :      #05  il 0000009f  at GoogleARCore.ARCoreSession.OnEnable () [0x00006] in D:\Unity3dProjects\ARCoreMovement\Assets\GoogleARCore\SDK\Scripts\ARCoreSession.cs:81
09-29 18:37:25.463 21064 21122 E CRASH   :      #06  il 0000013b  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <IL 0x0001c, 0x0013b>
09-29 18:37:25.471 21064 21122 E CRASH   :      #00  pc 000225d3  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libmono.so
09-29 18:37:25.471 21064 21122 E CRASH   :      #01  pc 001f7bb8  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libmono.so (mono_runtime_invoke+136)
09-29 18:37:25.471 21064 21122 E CRASH   :      #02  pc 00fbbc84  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)+84)
09-29 18:37:25.471 21064 21122 E CRASH   :      #03  pc 00dcb554  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (MonoBehaviour::AddToManager()+336)
09-29 18:37:25.471 21064 21122 E CRASH   :      #04  pc 00dcb094  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (MonoBehaviour::AwakeFromLoad(AwakeFromLoadMode)+656)
09-29 18:37:25.471 21064 21122 E CRASH   :      #05  pc 00fc3ee0  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQu
adMode)+108)
09-29 18:37:25.471 21064 21122 E CRASH   :      #06  pc 00fc3d2c  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (AwakeFromLoadQueue::PersistentManagerAwakeFromLoad()+24)
09-29 18:37:25.471 21064 21122 E CRASH   :      #07  pc 00f854c0  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (LoadSceneOperation::CompleteAwakeSequence()+84)
09-29 18:37:25.471 21064 21122 E CRASH   :      #08  pc 00f85500  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (LoadSceneOperation::CompletePreloadManagerLoadScene()+24)
09-29 18:37:25.471 21064 21122 E CRASH   :      #09  pc 00f851dc  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (LoadSceneOperation::PlayerLoadSceneFromThread()+328)
09-29 18:37:25.472 21064 21122 E CRASH   :      #10  pc 00f85264  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (LoadSceneOperation::CompleteLoadFirstScene()+4)
09-29 18:37:25.472 21064 21122 E CRASH   :      #11  pc 00f84fd8  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (LoadSceneOperation::IntegrateMainThread()+196)
09-29 18:37:25.472 21064 21122 E CRASH   :      #12  pc 00f85dc0  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (PreloadManager::UpdatePreloadingSingleStep(PreloadManager::Updat
09-29 18:37:25.472 21064 21122 E CRASH   :      #13  pc 00f86428  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (PreloadManager::WaitForAllAsyncOperationsToComplete()+76)
09-29 18:37:25.472 21064 21122 E CRASH   :      #14  pc 0061d3d0  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (UnityPlayerLoop()+428)
09-29 18:37:25.472 21064 21122 E CRASH   :      #15  pc 00620ba4  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/lib/arm/libunity.so (nativeRender(_JNIEnv*, _jobject*)+52)
09-29 18:37:25.472 21064 21122 E CRASH   :      #16  pc 000089ab  /data/app/com.kakaboc.arcoremovement-lFF_1d-7sUADxEuCtqcIgA==/oat/arm/base.odex (oatexec+18859)
09-29 18:37:25.472 21064 21122 E CRASH   :
09-29 18:37:25.472 21064 21122 E CRASH   : memory near r4:
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903420 00000000 00000000 00000000 00000000  ................
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903430 ba903410 e5522898 00000000 00000000  .4...(R.........
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903440 00000000 00000003 00000001 00000000  ................
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903450 00000000 00000000 00000000 00000000  ................
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903460 00000000 00000000 ffffffff 00010000  ................
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903470 e5522a30 e5522b90 0000001d 00000140  0*R..+R.....@...
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903480 61727728 72657070 6e616d20 64656761  (wrapper managed
09-29 18:37:25.472 21064 21122 E CRASH   :     ba903490 2d6f742d 6974616e 20296576 74737953  -to-native) Syst
09-29 18:37:25.472 21064 21122 E CRASH   :     ba9034a0 542e6d65 61657268 676e6964 746e492e  em.Threading.Int
09-29 18:37:25.473 21064 21122 E CRASH   :     ba9034b0 6f6c7265 64656b63 6d6f433a 65726170  erlocked:Compare
09-29 18:37:25.473 21064 21122 E CRASH   :     ba9034c0 68637845 65676e61 79532820 6d657473  Exchange (System
09-29 18:37:25.473 21064 21122 E CRASH   :     ba9034d0 7463412e 266e6f69 7379532c 2e6d6574  .Action&,System.
09-29 18:37:25.473 21064 21122 E CRASH   :     ba9034e0 69746341 532c6e6f 65747379 63412e6d  Action,System.Ac
09-29 18:37:25.473 21064 21122 E CRASH   :     ba9034f0 6e6f6974 00000029 00000022 000000bc  tion)...".......
09-29 18:37:25.473 21064 21122 E CRASH   :     ba903500 61727728 72657070 74616e20 2d657669  (wrapper native-
09-29 18:37:25.473 21064 21122 E CRASH   :     ba903510 6d2d6f74 67616e61 20296465 676f6f47  to-managed) Goog
09-29 18:37:25.473 21064 21122 E CRASH   :
09-29 18:37:25.473 21064 21122 E CRASH   : memory near sl:
09-29 18:37:25.473 21064 21122 E CRASH   :     bab9cd30 00000000 ffffffff 00000000 00000000  ................
09-29 18:37:25.473 21064 21122 E CRASH   :     bab9cd40 00000001 ea000000 2fbb51a1 00057705  .........Q./.w..
09-29 18:37:25.473 21064 21122 E CRASH   :     bab9cd50 0007f2e0 00000000 0006fdfe 00000000  ................
09-29 18:37:25.473 21064 21122 E CRASH   :     bab9cd60 00000000 3f666666 00000000 00000000  ....fff?........
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cd70 ffffffff 00000037 00000000 00000000  ....7...........
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cd80 e1a00001 00000000 00000000 00000000  ................
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cd90 64616f4c 20676e69 6576656c e500306c  Loading level0..
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cda0 0000000e 00000000 ffffffff 00000044  ............D...
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cdb0 bc4e7230 00000000 6576656c e300306c  0rN.....level0..
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cdc0 e34c00da e5900000 00000006 00000000  ..L.............
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cdd0 ffffffff 00000044 da333aa0 00000000  ....D....:3.....
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cde0 ffffffff 00000037 00000002 00000002  ....7...........
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9cdf0 b6c71410 00000000 ffffffff 00000037  ............7...
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9ce00 00000009 00000027 b6c71610 00000000  ....'...........
09-29 18:37:25.474 21064 21122 E CRASH   :     bab9ce10 ffffffff 00000037 00000009 00000027  ....7.......'...
09-29 18:37:25.475 21064 21122 E CRASH   :     bab9ce20 b6c71810 00000000 ffffffff 00000037  ............7...
09-29 18:37:25.475 21064 21122 E CRASH   :
09-29 18:37:25.475 21064 21122 E CRASH   : memory near ip:
09-29 18:37:25.475 21064 21122 E CRASH   :     7fffffe0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     7ffffff0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000000 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000010 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000020 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000030 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000040 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000050 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.475 21064 21122 E CRASH   :     80000060 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     80000070 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     80000080 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     80000090 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     800000a0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     800000b0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     800000c0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :     800000d0 ffffffff ffffffff ffffffff ffffffff  ................
09-29 18:37:25.476 21064 21122 E CRASH   :
09-29 18:37:25.476 21064 21122 E CRASH   : code around pc:
09-29 18:37:25.476 21064 21122 E CRASH   :     e55ed2c8 3240daf3 db043a20 51f8e8b1 51f8e8a0  ..@2 :.....Q...Q
09-29 18:37:25.476 21064 21122 E CRASH   :     e55ed2d8 32203a20 ea5fd01a bf247c02 c078c978   : 2.._..|$.x.x.
09-29 18:37:25.476 21064 21122 E CRASH   :     e55ed2e8 e8b1bf44 e8a00180 ea5f0180 bf247c82  D........._..|$.
09-29 18:37:25.476 21064 21122 E CRASH   :     e55ed2f8 3b04f851 3b04f840 f831bf44 f8204b02  Q..;@..;D.1..K .
09-29 18:37:25.476 21064 21122 E CRASH   :     e55ed308 f0124b02 bf1c0f01 7003780b 01f0e8bd  .K.......x.p....
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed318 8001e8bd e1520003 9a000001 e52de004  ......R.......-.
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed328 fa000ccc e3520084 8a000015 e1a03000  ......R......0..
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed338 eee01b10 e2522020 3a000003 f2202150  ....  R....:P! .
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed348 e2522020 f403020d 2afffffc e2822020    R........*  ..
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed358 e3120010 0a000000 f4030a0d e1b0ce82  ................
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed368 3a000000 f403070d aa000000 f483080d  ...:............
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed378 e1b0cf82 44c31001 24c31001 24c31001  .......D...$...$
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed388 e12fff1e e92d40f1 e2603000 e2133003  ../..@-..0`..0..
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed398 e1530002 81a03002 e1a01c01 e1811421  ..S..0......!...
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed3a8 e1811821 e1b0cf83 24c01001 24c01001  !..........$...$
09-29 18:37:25.477 21064 21122 E CRASH   :     e55ed3b8 44c01001 e0522003 98bd80f1 e1a0c001  ...D. R.........
09-29 18:37:25.477 21064 21122 E CRASH   :
09-29 18:37:25.477 21064 21122 E CRASH   : code around lr:
09-29 18:37:25.477 21064 21122 E CRASH   :     c10e9768 60606868 60a068a8 692068e9 69a960e1  hh``.h.`.h i.`.i
09-29 18:37:25.477 21064 21122 E CRASH   :     c10e9778 eb68f7ff e9d56120 69296706 f7ff4632  ..h. a...g)i2F..
09-29 18:37:25.477 21064 21122 E CRASH   :     c10e9788 e9c4eb68 6a286706 b0016220 b570bdf0  h....g(j b....p.
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9798 4604461d fbf2f000 0610f104 46304621  .F.F........!F0F
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97a8 fc78f7ff 0030f104 462a4631 f95cf000  ..x...0.1F*F..\.
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97b8 32fff04f 1004e9dd 220066a2 f8a463e2  O..2.....f.".c..
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97c8 f884206c e9c4206e f104101c f7ff0040  l ..n ......@...
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97d8 4620ffb7 4601bd70 6bc82200 206cf881  .. Fp..F.".k..l
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97e8 bf182800 ba50f000 46014770 6bc82201  .(....P.pG.F.".k
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e97f8 206cf881 bf182800 bb1cf000 b5104770  ..l .(......pG..
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9808 f1044604 f7ff0010 4620fc85 f808f000  .F........ F....
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9818 28006be0 e8bdbf1c f0004010 bd10bb0f  .k.(.....@......
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9828 4604b510 006df894 6be0b370 bf182800  ...F..m.p..k.(..
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9838 f104bd10 f0000030 2801f999 2028d124  ....0......($.(
09-29 18:37:25.478 21064 21122 E CRASH   :     c10e9848 fc38f000 231ce9d4 f0004621 f894f9a9  ..8....#!F......
09-29 18:37:25.479 21064 21122 E CRASH   :     c10e9858 63e0106c bf182900 faecf000 006ef894  l..c.)........n.
09-29 18:37:25.482 21064 21122 E MessageQueue: IdleHandler threw exception
09-29 18:37:25.482 21064 21122 E MessageQueue: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
09-29 18:37:25.482 21064 21122 E MessageQueue: Build fingerprint: 'lge/lucye_global_com/lucye:8.0.0/OPR1.170623.032/182292118abf4:user/release-keys'
09-29 18:37:25.482 21064 21122 E MessageQueue: Revision: '12'
09-29 18:37:25.482 21064 21122 E MessageQueue: pid: 21064, tid: 21122, name: UnityMain  >>> com.kakaboc.arcoremovement <<<
09-29 18:37:25.482 21064 21122 E MessageQueue:     r0 00000000  r1 00000000  r2 e5402fc8  r3 00000000
09-29 18:37:25.482 21064 21122 E MessageQueue:     r4 ba903440  r5 d93fe248  r6 e5402fc8  r7 e55c7fc0
09-29 18:37:25.482 21064 21122 E MessageQueue:     r8 00000000  r9 00000003  sl bab9cd50  fp d93fe1a8
09-29 18:37:25.482 21064 21122 E MessageQueue:     ip 80000000  sp d93fe154  lr c10e978b  pc e55ed2ea  cpsr e7a0fc90
09-29 18:37:25.482 21064 21122 E MessageQueue:
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libc.__memcpy_base_aligned(__memcpy_base_aligned:113)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libarpresto_api.ArPrestoConfig_copy(ArPrestoConfig const&, ArPrestoConfig*)(ArPrestoConfig_copy:42)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at ExternApi.ArPresto_setConfiguration(Native Method)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at ARCoreAndroidLifecycleManager._SetConfiguration(ARCoreAndroidLifecycleManager.cs:280)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at ARCoreAndroidLifecycleManager.EnableSession(ARCoreAndroidLifecycleManager.cs:104)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at ARCoreSession.OnEnable(ARCoreSession.cs:81)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at Object.runtime_invoke_void__this__(Native Method)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libmono.000225d3(Native Method)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libmono.mono_runtime_invoke(mono_runtime_invoke:136)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)(Invoke:84)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.MonoBehaviour::AddToManager()(AddToManager:336)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.MonoBehaviour::AwakeFromLoad(AwakeFromLoadMode)(AwakeFromLoad:656)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode)(InvokePersistentManagerAwake:108)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.AwakeFromLoadQueue::PersistentManagerAwakeFromLoad()(PersistentManagerAwakeFromLoad:24)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.LoadSceneOperation::CompleteAwakeSequence()(CompleteAwakeSequence:84)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.LoadSceneOperation::CompletePreloadManagerLoadScene()(CompletePreloadManagerLoadScene:24)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.LoadSceneOperation::PlayerLoadSceneFromThread()(PlayerLoadSceneFromThread:328)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.LoadSceneOperation::CompleteLoadFirstScene()(CompleteLoadFirstScene:4)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.LoadSceneOperation::IntegrateMainThread()(IntegrateMainThread:196)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.PreloadManager::UpdatePreloadingSingleStep(PreloadManager::UpdatePreloadingFlags, int)(UpdatePreloadingSingleStep:416)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.PreloadManager::WaitForAllAsyncOperationsToComplete()(WaitForAllAsyncOperationsToComplete:76)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.UnityPlayerLoop()(UnityPlayerLoop:428)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at libunity.nativeRender(_JNIEnv*, _jobject*)(nativeRender:52)
09-29 18:37:25.482 21064 21122 E MessageQueue:  at base.oatexec(oatexec:18859)
09-29 18:37:28.769  3620  4377 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=22, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
09-29 18:37:50.240  3620  4377 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=19, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
09-29 18:37:55.753 21404 21404 E QCALOG  : [mlid] Failed to load libminksocket

```
If that's not relevant for Issue please close.
Thanks in advance

**Comment by pablisho** [comment]
Hi, the recommended way to update the plugin is to remove the GoogleARCore folder entirely and then reimport.
