### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by siny-yao** [google-ar/arcore-unity-sdk#470]
### VERSIONS USED
- Unity:2017.4.15
- ARCore SDK for Unity: ARCore SDK for Unity v1.6.0
I upgraded ARCore from 1.5 to 1.6 and exported the project, importing the following error in android studio
java.lang.UnsatisfiedLinkError: No implementation found for void com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator() (tried Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator and Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator__)
        at com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator(Native Method)
        at com.unity3d.player.UnityPlayer.resume(Unknown Source:37)
        at com.linkon.unity.ar.UnityPlayerActivity.onResume(UnityPlayerActivity.java:57)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7300)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by fredsa** [comment]
Please try building and running directly from Unity.

Issues with Unity build export and Android Studio import are best addressed in by those communities.
