### ISSUE TITLE
Unity application crashed randomly on android devices

### ISSUE THREAD

**Issue by lleo52** [google-ar/arcore-unity-sdk#553]
Unity application crashed randomly on android devices.

### SPECIFIC ISSUE ENCOUNTERED

1. Run my ARCore Unity Application.
2. searching ground planes.
3. searched a ground plane.
4. place a my 3d objecs on searched ground plane.
5. lost tracking forcingly (Cover the camera lens with my hand)
**6. ARCore searching ground planes in trackable statate
   => Crash point**

### VERSIONS USED
- Unity: 2018.3.13
- ARCore SDK for Unity: 1.8.0
- Device manufacturer, model, and O/S: Samsung Galaxy S7
- ARCore: 

04-30 18:09:22.581 23916 24029 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000160

04-30 18:09:22.581 23916 24029 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

04-30 18:09:22.581 23916 24029 E CRASH   : Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a'

04-30 18:09:22.581 23916 24029 E CRASH   : Build fingerprint: 'samsung/heroltelgt/heroltelgt:8.0.0/R16NW/G930LKLU2ESA2:user/release-keys'

04-30 18:09:22.581 23916 24029 E CRASH   : Revision: '8'

04-30 18:09:22.581 23916 24029 E CRASH   : pid: 23916, tid: 24029, name: trck03  >>> com.snowball.gamater_ar <<<

04-30 18:09:22.581 23916 24029 E CRASH   :     r0 00038971  r1 00000000  r2 ad6e5000  r3 00000160

04-30 18:09:22.581 23916 24029 E CRASH   :     r4 000000fa  r5 bed84ed0  r6 b8d8b710  r7 b8d8b720

04-30 18:09:22.581 23916 24029 E CRASH   :     r8 00000000  r9 00000016  sl bed84d20  fp 000000fa

04-30 18:09:22.581 23916 24029 E CRASH   :     ip ed198d58  sp bed84ce8  lr c05f054d  pc c05f0590  cpsr 00005ddd

04-30 18:09:22.581 23916 24029 E CRASH   : 

04-30 18:09:22.581 23916 24029 E CRASH   : backtrace:

04-30 18:09:22.626  3647  3669 E memtrack: Couldn't load memtrack module

04-30 18:09:22.667  3647  3669 E memtrack: Couldn't load memtrack module

04-30 18:09:22.735  3647  3669 E memtrack: Couldn't load memtrack module

04-30 18:09:23.140 23916 24029 E CRASH   : 	#00  pc 00170590  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#01  pc 00170f17  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#02  pc 0016cf39  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#03  pc 0016c755  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#04  pc 0016b53f  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#05  pc 0016a6af  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#06  pc 00128005  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#07  pc 00127e25  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#08  pc 0012ac4f  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#09  pc 000cc8c3  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#10  pc 000fc6b7  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#11  pc 000fc83d  /data/app/com.google.ar.core-J4up7Inrk9X0Pkhc3eVuFw==/lib/arm/libarcore_c.so

04-30 18:09:23.140 23916 24029 E CRASH   : 	#12  pc 00048a89  /system/lib/libc.so (__pthread_start(void*)+24)

04-30 18:09:23.140 23916 24029 E CRASH   : 	#13  pc 0001b34f  /system/lib/libc.so (__start_thread+32)

04-30 18:09:23.140 23916 24029 E CRASH   : 

04-30 18:09:23.140 23916 24029 E CRASH   : memory near r0:

04-30 18:09:23.141 23916 24029 E CRASH   :     00038950 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     00038960 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     00038970 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     00038980 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     00038990 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     000389a0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     000389b0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.141 23916 24029 E CRASH   :     000389c0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     000389d0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     000389e0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     000389f0 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     00038a00 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     00038a10 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     00038a20 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     00038a30 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   :     00038a40 ffffffff ffffffff ffffffff ffffffff  ................

04-30 18:09:23.142 23916 24029 E CRASH   : 

04-30 18:09:23.142 23916 24029 E CRASH   : memory near r2:

04-30 18:09:23.142 23916 24029 E CRASH   :     ad6e4fe0 0000b00d 4147bbf2 00000000 00000000  ......GA........

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e4ff0 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5000 00000064 00000019 00000000 00000000  d...............

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5010 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5020 00000064 b11abc60 00000000 00000000  d...`...........

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5030 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5040 00000064 000000d3 00000000 00000000  d...............

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5050 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5060 00000064 00000012 00000000 00000000  d...............

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5070 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.143 23916 24029 E CRASH   :     ad6e5080 00000064 b11ace40 00000000 00000000  d...@...........

04-30 18:09:23.144 23916 24029 E CRASH   :     ad6e5090 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.144 23916 24029 E CRASH   :     ad6e50a0 00000064 000000c5 00000000 00000000  d...............

04-30 18:09:23.144 23916 24029 E CRASH   :     ad6e50b0 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.144 23916 24029 E CRASH   :     ad6e50c0 00000064 0000000e 00000000 00000000  d...............

04-30 18:09:23.144 23916 24029 E CRASH   :     ad6e50d0 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.144 23916 24029 E CRASH   : 

04-30 18:09:23.144 23916 24029 E CRASH   : memory near r5:

04-30 18:09:23.144 23916 24029 E CRASH   :     bed84eb0 836c7758 3f9458a8 ad6e5000 ad6e5000  Xwl..X.?.Pn..Pn.

04-30 18:09:23.144 23916 24029 E CRASH   :     bed84ec0 ad6e6f40 ad647400 ad647400 ad6477e8  @on..td..td..wd.

04-30 18:09:23.144 23916 24029 E CRASH   :     bed84ed0 adbd7010 000000fa ae110810 000000fa  .p..............

04-30 18:09:23.144 23916 24029 E CRASH   :     bed84ee0 6aeee33e 400dcfd8 ed6501e3 c010f65b  >..j...@..e.[...

04-30 18:09:23.144 23916 24029 E CRASH   :     bed84ef0 2a621658 c0135be7 93e86aae 3f91917a  X.b*.[...j..z..?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f00 434349ec 3f79a216 e205a635 3ff0115f  .ICC..y?5..._..?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f10 b0444d58 b0444d60 06ff0101 3f5363dc  XMD.`MD......cS?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f20 6aeee33e 400dcfd8 ed6501e3 c010f65b  >..j...@..e.[...

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f30 2a621658 c0135be7 bed85008 00000001  X.b*.[...P......

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f40 c0aa5319 bfe5c025 8a2b81c9 3fe18c1b  .S..%.....+....?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f50 7155cf15 3fd625b6 50bf7f5a 3fd5f187  ..Uq.%.?Z..P...?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f60 99bdbc8e c014de69 89047f2c 40152bce  ....i...,....+.@

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f70 89307b18 3fcf4957 3a92a305 c0239d01  .{0.WI.?...:..#.

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f80 c0aa5319 3fe5c025 8a2b81c9 bfe18c1b  .S..%..?..+.....

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84f90 7155cf15 bfd625b6 50bf7f5a 3fd5f187  ..Uq.%..Z..P...?

04-30 18:09:23.145 23916 24029 E CRASH   :     bed84fa0 c0aa5319 bfe5c025 8a2b81c9 3fe18c1b  .S..%.....+....?

04-30 18:09:23.145 23916 24029 E CRASH   : 

04-30 18:09:23.145 23916 24029 E CRASH   : memory near r6:

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b6f0 00000000 55440001 00000000 00000101  ......DU........

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b700 ffffffff ffffffff ffffffff b8d8b700  ................

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b710 c1401178 00000011 00000000 407e511e  x.@..........Q~@

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b720 cb9cab0c c0147649 16273f26 4028bfde  ....Iv..&?'...(@

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b730 8f7702d7 bfd9419a 00000000 7ff80000  ..w..A..........

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b740 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b750 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b760 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b770 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.146 23916 24029 E CRASH   :     b8d8b780 e15f9d39 bfcd5151 e2d148b8 bfd30f10  9._.QQ...H......

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b790 4fd483aa 3fc413cb b0e5ec00 b0e5ed40  ...O...?....@...

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b7a0 b0e5ee00 4073d191 dc6206d5 0cd5ce96  ......s@..b.....

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b7b0 00000000 55440001 00000000 00000101  ......DU........

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b7c0 ffffffff ffffffff ffffffff b8d8b7c0  ................

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b7d0 c1401178 00000007 00000000 407e511e  x.@..........Q~@

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b7e0 fe0cb928 c019522d 5225eba2 402cea14  (...-R....%R..,@

04-30 18:09:23.147 23916 24029 E CRASH   : 

04-30 18:09:23.147 23916 24029 E CRASH   : memory near r7:

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b700 ffffffff ffffffff ffffffff b8d8b700  ................

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b710 c1401178 00000011 00000000 407e511e  x.@..........Q~@

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b720 cb9cab0c c0147649 16273f26 4028bfde  ....Iv..&?'...(@

04-30 18:09:23.147 23916 24029 E CRASH   :     b8d8b730 8f7702d7 bfd9419a 00000000 7ff80000  ..w..A..........

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b740 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b750 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b760 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b770 00000000 7ff80000 00000000 7ff80000  ................

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b780 e15f9d39 bfcd5151 e2d148b8 bfd30f10  9._.QQ...H......

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b790 4fd483aa 3fc413cb b0e5ec00 b0e5ed40  ...O...?....@...

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b7a0 b0e5ee00 4073d191 dc6206d5 0cd5ce96  ......s@..b.....

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b7b0 00000000 55440001 00000000 00000101  ......DU........

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b7c0 ffffffff ffffffff ffffffff b8d8b7c0  ................

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b7d0 c1401178 00000007 00000000 407e511e  x.@..........Q~@

04-30 18:09:23.148 23916 24029 E CRASH   :     b8d8b7e0 fe0cb928 c019522d 5225eba2 402cea14  (...-R....%R..,@

04-30 18:09:23.149 23916 24029 E CRASH   :     b8d8b7f0 b438dd9a 3ff0d7f0 00000000 7ff80000  ..8....?........

04-30 18:09:23.149 23916 24029 E CRASH   : 

04-30 18:09:23.149 23916 24029 E CRASH   : memory near sl:

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d00 ad9f1f40 b01a2220 00001f40 00000096  @... "..@.......

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d10 ad9f0000 000001bf ae10c040 000000fa  ........@.......

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d20 675b9555 29b6bef8 d8048fdc 2d6c0cc8  U.[g...)......l-

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d30 b8d8b720 b8d8b710 9d0d2764 00038971   .......d'..q...

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d40 acefe000 acefe708 acefe708 ade93bd0  .............;..

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d50 b01ee780 b01ef590 b01f3280 b628a000  .........2....(.

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d60 b628a4b0 b628b900 b4f29c10 00000096  ..(...(.........

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d70 00000084 0000000b 00000000 00000000  ................

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d80 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.149 23916 24029 E CRASH   :     bed84d90 06ff0101 3f5363dc b58007ab 3f416560  .....cS?....`eA?

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84da0 9ef092f2 3f2283b2 d08fcfec 3f7400e0  ......"?......t?

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84db0 3e3c7bb1 3f89c86b 88e368f1 3ee4f8b5  .{<>k..?.h.....>

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84dc0 88e368f1 3ee4f8b5 88e368f1 3ee4f8b5  .h.....>.h.....>

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84dd0 88e368f1 3ee4f8b5 88e368f1 3ee4f8b5  .h.....>.h.....>

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84de0 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84df0 3a92a305 c0239d01 d8ec0ab7 3e92e9ef  ...:..#........>

04-30 18:09:23.150 23916 24029 E CRASH   : 

04-30 18:09:23.150 23916 24029 E CRASH   : memory near sp:

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84cc8 00000000 000000fa 000000fa 00000000  ................

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84cd8 000000fa bed84eb8 b8d8b720 c05f054d  .....N.. ...M._.

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84ce8 bed84d40 00000320 00000040 bed84d68  @M.. ...@...hM..

04-30 18:09:23.150 23916 24029 E CRASH   :     bed84cf8 bed84d5c bed84d50 ad9f1f40 b01a2220  \M..PM..@... "..

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d08 00001f40 00000096 ad9f0000 000001bf  @...............

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d18 ae10c040 000000fa 675b9555 29b6bef8  @.......U.[g...)

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d28 d8048fdc 2d6c0cc8 b8d8b720 b8d8b710  ......l- .......

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d38 9d0d2764 00038971 acefe000 acefe708  d'..q...........

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d48 acefe708 ade93bd0 b01ee780 b01ef590  .....;..........

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d58 b01f3280 b628a000 b628a4b0 b628b900  .2....(...(...(.

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d68 b4f29c10 00000096 00000084 0000000b  ................

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d78 00000000 00000000 00000000 00000000  ................

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d88 00000000 00000000 06ff0101 3f5363dc  .............cS?

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84d98 b58007ab 3f416560 9ef092f2 3f2283b2  ....`eA?......"?

04-30 18:09:23.151 23916 24029 E CRASH   :     bed84da8 d08fcfec 3f7400e0 3e3c7bb1 3f89c86b  ......t?.{<>k..?

04-30 18:09:23.152 23916 24029 E CRASH   :     bed84db8 88e368f1 3ee4f8b5 88e368f1 3ee4f8b5  .h.....>.h.....>

04-30 18:09:23.152 23916 24029 E CRASH   : 

04-30 18:09:23.152 23916 24029 E CRASH   : code around pc:

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f0570 1309eb08 0b00edc1 0b02edd7 0b02edc1  ................

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f0580 0b04edd7 0b04edc1 1200e9d5 1a519d5f  ............_.Q.

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f0590 0b00edd3 eb05682d edc10161 edd30b00  ....-h..a.......

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f05a0 9b600b02 0b02edc1 1201e9d3 d0044291  ..`..........B..

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f05b0 68586008 60583004 a915e003 f7634618  .`Xh.0X`.....Fc.

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f05c0 9d61fe43 0101e9d5 d2114288 0110f100  C.a......B......

04-30 18:09:23.152 23916 24029 E CRASH   :     c05f05d0 f9014605 21148acf 8ac1f905 dd28f30e  .F.....!......(.

04-30 18:09:23.153 23916 24029 E CRASH   :     c05f05e0 60292100 61019d61 30206868 e0036068  .!)`a..ahh 0h`..

04-30 18:09:23.153 23916 24029 E CRASH   :     c05f05f0 f0024628 6868ff39 2e009915 1c08f840  (F..9.hh....@...

04-30 18:09:23.153 23916 24029 E CRASH   :     c05f0600 0120f1a0 0acff96a f941465c d0070acf  .. .j...\FA.....

04-30 18:09:23.153 23916 24029 E CRASH   :     c05f0610 e8511d31 32012f00 2300e841 d1f82b00  1.Q../.2A..#.+..

04-30 18:09:23.153 23916 24029 E CRASH   :     c05f0620 7c10f840 7c0cf850 6c0cf840 b1af9e0a  @..|P..|@..l....

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f0630 f3bf1d38 e8508f5b 1e4a1f00 2300e840  8...[.P...J.@..#

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f0640 d1f82b00 f3bf2900 d1078f5b 68816838  .+...)..[...8h.h

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f0650 47884638 f3574638 465cdf45 b1af9f13  8F.G8FW.E.\F....

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f0660 f3bf1d38 e8508f5b 1e4a1f00 2300e840  8...[.P...J.@..#

04-30 18:09:23.154 23916 24029 E CRASH   : 

04-30 18:09:23.154 23916 24029 E CRASH   : code around lr:

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f052c 97122e00 d007600e e8501d30 31011f00  .....`..0.P....1

04-30 18:09:23.154 23916 24029 E CRASH   :     c05f053c 1200e840 d1f82a00 4649980c db5af250  @....*....IFP.Z.

04-30 18:09:23.155 23916 24029 E CRASH   :     c05f054c f8979015 2901109d 81b7f040 1200e9d5  .......)@.......

04-30 18:09:23.158 23916 24029 E CRASH   :     c05f055c 1a519b5e 0b00edd7 681b1149 0141eb01  ^.Q.....I..h..A.

04-30 18:09:23.158 23916 24029 E CRASH   :     c05f056c 01c1eb03 1309eb08 0b00edc1 0b02edd7  ................

04-30 18:09:23.159 23916 24029 E CRASH   :     c05f057c 0b02edc1 0b04edd7 0b04edc1 1200e9d5  ................

04-30 18:09:23.160 23916 24029 E CRASH   :     c05f058c 1a519d5f 0b00edd3 eb05682d edc10161  _.Q.....-h..a...

04-30 18:09:23.160 23916 24029 E CRASH   :     c05f059c edd30b00 9b600b02 0b02edc1 1201e9d3  ......`.........

04-30 18:09:23.160 23916 24029 E CRASH   :     c05f05ac d0044291 68586008 60583004 a915e003  .B...`Xh.0X`....

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f05bc f7634618 9d61fe43 0101e9d5 d2114288  .Fc.C.a......B..

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f05cc 0110f100 f9014605 21148acf 8ac1f905  .....F.....!....

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f05dc dd28f30e 60292100 61019d61 30206868  ..(..!)`a..ahh 0

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f05ec e0036068 f0024628 6868ff39 2e009915  h`..(F..9.hh....

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f05fc 1c08f840 0120f1a0 0acff96a f941465c  @..... .j...\FA.

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f060c d0070acf e8511d31 32012f00 2300e841  ....1.Q../.2A..#

04-30 18:09:23.161 23916 24029 E CRASH   :     c05f061c d1f82b00 7c10f840 7c0cf850 6c0cf840  .+..@..|P..|@..l

04-30 18:09:23.193 23916 23933 E CRASH   : other thread is trapped; signum = 11

04-30 18:09:23.194 23916 23933 E MessageQueue: IdleHandler threw exception

04-30 18:09:23.194 23916 23933 E MessageQueue: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000160

04-30 18:09:23.194 23916 23933 E MessageQueue: Build fingerprint: 'samsung/heroltelgt/heroltelgt:8.0.0/R16NW/G930LKLU2ESA2:user/release-keys'

04-30 18:09:23.194 23916 23933 E MessageQueue: Revision: '8'

04-30 18:09:23.194 23916 23933 E MessageQueue: pid: 23916, tid: 24029, name: trck03  >>> com.snowball.gamater_ar <<<

04-30 18:09:23.194 23916 23933 E MessageQueue:     r0 00038971  r1 00000000  r2 ad6e5000  r3 00000160

04-30 18:09:23.194 23916 23933 E MessageQueue:     r4 000000fa  r5 bed84ed0  r6 b8d8b710  r7 b8d8b720

04-30 18:09:23.194 23916 23933 E MessageQueue:     r8 00000000  r9 00000016  sl bed84d20  fp 000000fa

04-30 18:09:23.194 23916 23933 E MessageQueue:     ip ed198d58  sp bed84ce8  lr c05f054d  pc c05f0590  cpsr 00005ddd

04-30 18:09:23.194 23916 23933 E MessageQueue: 

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.00170590(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.00170f17(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.0016cf39(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.0016c755(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.0016b53f(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.0016a6af(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.00128005(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.00127e25(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.0012ac4f(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.000cc8c3(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.000fc6b7(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libarcore_c.000fc83d(Native Method)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libc.__pthread_start(void*)(__pthread_start:24)

04-30 18:09:23.194 23916 23933 E MessageQueue: 	at libc.__start_thread(__start_thread:32)

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by FUBAR2077** [comment]
This also happens on my device - Samsung Galaxy S7, Android ver. 8.0.0
