### ISSUE TITLE
Crash of ImageReader-640 on Pixel 2 XL

### ISSUE THREAD

**Issue by brookman** [google-ar/arcore-unity-sdk#622]
### SPECIFIC ISSUE ENCOUNTERED
App crashes some times when starting it.

```
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: FATAL EXCEPTION: main
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: Process: [package-name].dev, PID: 26176
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000005c
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: Build fingerprint: 'google/taimen/taimen:9/PQ3A.190705.001/5565753:user/release-keys'
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: Revision: 'rev_10'
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: pid: 26176, tid: 26832, name: ImageReader-640  >>> [package-name].dev <<<
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime:     r0 00000050  r1 00000014  r2 00000008  r3 00000000
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime:     r4 a37911a8  r5 a3791080  r6 00000004  r7 a1e71e2c
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime:     r8 a3791190  r9 b487f3f4  sl b487f3f8  fp a3791194
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime:     ip 0000000a  sp b487f290  lr a905f9db  pc a905fa5a  cpsr 000068d0
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.004d5a5a(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.004d5977(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.000fd13f(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.000fce45(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.00101919(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.0021fda5(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.0021cb87(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.00205903(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.0022b803(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.002c1f67(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libarcore_c.00df1a3b(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libmediandk.0001094f(Native Method)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libstagefright_foundation.android::AHandler::deliverMessage(android::sp<android::AMessage> const&)(AHandler:24)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libstagefright_foundation.android::AMessage::deliver()(AMessage:64)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libstagefright_foundation.android::ALooper::loop()(ALooper:472)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libutils.android::Thread::_threadLoop(void*)(Thread:290)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libandroid_runtime.android::AndroidRuntime::javaThreadShell(void*)(AndroidRuntime:82)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libc.__pthread_start(void*)(__pthread_start:22)
08-08 11:58:07.058 10838 26176 26176 E AndroidRuntime: 	at libc.__start_thread(__start_thread:24)
08-08 11:58:07.274  1000  1197  8794 W ActivityManager:   Force finishing activity [package-name].dev/[package-name].MainActivity
```

### VERSIONS USED
- Unity: 2019.1.8f1
- ARCore SDK for Unity: 1.9.0
- Device manufacturer, model, and O/S:  Google Pixel 2 XL, PQ3A.190705.001
- ARCore: 1.11.190715106
- Output of `adb shell getprop ro.build.fingerprint`: google/taimen/taimen:9/PQ3A.190705.001/5565753:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Start an ARCore Unity app

**Comment by nilsk123** [comment]
I'm seeing this still in crashlytics logs, seems to only happen in scenes that use imagetracking
