### ISSUE TITLE
Augmented Image Crash Issue on Pixel 2

### ISSUE THREAD

**Issue by cvasquez-github** [google-ar/arcore-unity-sdk#639]
### SPECIFIC ISSUE ENCOUNTERED
The app crashes, in Google Pixel 2 device, when enabling Image Targets.
The exactly same app (same apk) runs perfectly fine in other devices.
The Augmented Image size is set to 12cms - 0.12 meters

Noticed the following messages on the log:
- Property calibration_cad is not defined
- Could not open /data/user/0/XXX.XXX.XX/cache/arcore-online-recalibration for reading
- Couldn't find entry in device profile
- Image width in meters must be greater than 0

LOG MESSAGES: 
09-06 19:40:51.177 17665 17681 I third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 190715186
09-06 19:40:51.177 17665 17681 I third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.9
09-06 19:40:51.204 17665 17681 I native  : version_check.cc:23 ARCore Version: APK version:1.11.190715186
09-06 19:40:51.204 17665 17681 I native  : version_check.cc:24 ARCore Version: emulated SDK version:1.9.190412000
19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:434 Found nothing for S9npar
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:434 Found nothing for walleye/walleye
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:419 Considering QsSAVR:9
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:419 Considering QsSAVR:8.1
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:419 Considering QsSAVR:8.0
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:419 Considering QsSAVR:O
09-06 19:40:51.242 17588 17600 I native  : device_profile_database_helpers.cc:430 Device profile for google/walleye/walleye:9/PQ3A.190801.002/5670241:user/release-keys: QsSAVR:9
09-06 19:40:51.244 17588 17600 W native  : helpers.cc:2129 Defaulting to persistent calibration file.
09-06 19:40:51.244 17588 17600 W native  : helpers.cc:2137 Setting factory calibration from Android property. This method will be deprecated in API >= 24.
09-06 19:40:51.244 17588 17600 W native  : helpers.cc:2106 Property calibration_cad is not defined.
09-06 19:40:51.244 17588 17600 I native  : calibration_provider.cc:672 Will merge factory calibration from /persist/sensors/calibration/calibration.xml with loaded calibration config.
09-06 19:40:51.245 17588 17600 I native  : calibration_jni.cc:237 Attempting to merge in factory calibration.
09-06 19:40:51.245 17588 17600 W native  : device_profile2_proto_io.h:433 Couldn't find entry in device profile for transformation from 100 to 3
09-06 19:40:51.245 17588 17600 W native  : device_profile2_proto_io.h:433 Couldn't find entry in device profile for transformation from 100 to 1
09-06 19:40:51.247 17665 17681 I native  : session_create_implementation_shared.cc:752 Persistent online recalibration is enabled by Phenotype.
09-06 19:40:51.247 17665 17681 I native  : online_calibration_manager.cc:53 OnlineCalibrationManager: Could not open /data/user/0/com.vridge.ronin.ar/cache/arcore-online-recalibration for reading.

native  : status.cc:153 generic::invalid_argument: Image width in meters must be greater than 0
java.lang.RuntimeException
Caused by: com.google.ar.core.exceptions.FatalException
09-06 19:40:51.503 17665 17761 E AndroidRuntime:        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:59)
09-06 19:40:51.503 17665 17761 E AndroidRuntime:        at com.google.ar.core.AugmentedImageDatabase.nativeAddImageWithPhysicalSize(Native Method)
09-06 19:40:51.503 17665 17761 E AndroidRuntime:        at com.google.ar.core.AugmentedImageDatabase.addImage(Unknown Source:25)

### VERSIONS USED
- Unity: Unity 2018.4.6f1, 2019.1.6f1 and 2019.2.0f1
- ARCore SDK for Unity:  ArCore 1.9
- Device manufacturer, model, and O/S:  Google Pixel 2 Android 9 PQ3A.190801.002
- ARCore:  versionName=1.11.190715186 Hidden system packages:  versionName=0
- Output of `adb shell getprop ro.build.fingerprint`: 
google/walleye/walleye:9/PQ3A.190801.002/5670241:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by cvasquez-github** [comment]
UPDATE:
It works on Google Pixel after updating to Android 10.
So, seems to be an issue with Android 9 and running the app in 64bits!

FAILED - ANDROID 9
09-06 19:40:50.155 17665 17681 I Adreno  : QUALCOMM build                   : 6fb5a5b, Ife855c4895
09-06 19:40:50.155 17665 17681 I Adreno  : Build Date                       : 08/21/18
09-06 19:40:50.155 17665 17681 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.00.00
09-06 19:40:50.155 17665 17681 I Adreno  : Build Config                     : S L 4.0.10 AArch64
device_profile_database_helpers.cc:430 Device profile for google/walleye/walleye:9/PQ3A.190801.002/5670241:user/release-keys: QsSAVR:9

WORKED - ANDROID 10
08 16:07:49.498  6561  6582 I Adreno  : QUALCOMM build                   : bc00834, I609ab310b2
09-08 16:07:49.498  6561  6582 I Adreno  : Build Date                       : 04/11/19
09-08 16:07:49.498  6561  6582 I Adreno  : OpenGL ES Shader Compiler Version: EV031.26.07.00
09-08 16:07:49.498  6561  6582 I Adreno  : Build Config                     : S L 8.0.6 AArch64
device_profile_database_helpers.cc:430 Device profile for google/walleye/walleye:10/QP1A.190711.020/5800535:user/release-keys: QsSAVR:9
